# NUMPY
Numpy (abr. for Numerical Python) is a python library for numerical computing using multidimentional array and many mathematical functions to operate on these arrays.

Numpy array | Python sequence type
------------|----------------------
instance of `ndarray` class implement in C | build-in class - `list`, `tuple`
faster execution and memory efficient | slower execution due to overhead and discrete storage
homogeneous | heterogeneous
values store in consecutive memory locations | contains references to discrete memory location that stores the values
vactorization and broadcasting | no vectorization and broadcasting
more functionality | less functionality
More flexible and advanced slicing - boolean and fancy indexing, multidimentional slicing | simple indexing/ slicing
more flexible data types | less flexible data types


In [9]:
#NumPy array
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.dtype)

b = np.array([[7.2, 8, 9], [10, 11, 12]])
print(b)
print(b.dtype)

#c = np.array([[1, 2, 3], [4, 5]])
#This will raise an error because the inner lists are not of the same length

[[1 2 3]
 [4 5 6]]
int64
[[ 7.2  8.   9. ]
 [10.  11.  12. ]]
float64


In [ ]:
#NumPy array attributes
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.ndim)   # Number of dimensions
print(a.shape)  # Shape of the array - tuple of array dimensions
print(a.size)   # Total number of elements - products of the shape dimensions
print(a.dtype)  # Data type of the elements
print(a.itemsize)  # Size of each element in bytes
print(a.nbytes) # Total bytes consumed by the elements of the array -> a.size * a.itemsize

2
(2, 3)
6
int64
8
48
[[1 4]
 [2 5]
 [3 6]]


In [12]:
lst = [1, 2, 3]
a = np.array(lst)
print(a)

tup = (1, 2, 3)
a = np.array(tup)
print(a)

ran1 = np.arange(7)         #more efficient than range
ran2 = np.array(range(7))
print(ran1, ran2)

[1 2 3]
[1 2 3]
[0 1 2 3 4 5 6] [0 1 2 3 4 5 6]


In [ ]:
a = np.array(48)    #scalar - 0D array
print(a.ndim, a.shape, a.size, a)
b = np.array([48])  #1D array with one element
print(b.ndim, b.shape, b.size, b)

a = np.array([1,2,3])   #1D array
print(a.ndim, a.shape, a.size, a)
b = np.array([[1,2,3], [4,5,6]])  #2D array
print(b.ndim, b.shape, b.size)
print(b)
c = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])  #3D array
print(c.ndim, c.shape, c.size)
print(c)

e = np.array([1, 2, 3, 4], ndmin=5)     #5D array with one row
print(e.ndim, e.shape, e.size)
print(e)
e = np.array([[1, 2, 3, 4], [1,2,4,3]], ndmin=5)     #5D array with two rows
print(e.ndim, e.shape, e.size)
print(e)

0 () 1 48
1 (1,) 1 [48]
1 (3,) 3 [1 2 3]
2 (2, 3) 6
[[1 2 3]
 [4 5 6]]
3 (2, 2, 3) 12
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
5 (1, 1, 1, 1, 4) 4
[[[[[1 2 3 4]]]]]
5 (1, 1, 1, 2, 4) 8
[[[[[1 2 3 4]
    [1 2 4 3]]]]]


In [7]:
z = np.zeros((2, 3))  #2D array of zeros
print(z)
z = np.zeros((2, 3), dtype=np.int8)  #2D array of zeros (int)
print(z)

o = np.ones((2, 3, 2))  #3D array of ones
print(o)

f = np.full((2, 3), 7)  #2D array filled with 7
print(f)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
[[7 7 7]
 [7 7 7]]


In [ ]:
#functions on arrays
print(np.sum(a))  # Sum of all elements
print(np.sum(a, axis=0))  # Sum along the first axis (columns)

print(a.T)      # Transpose of the array